### ISSUE TITLE
领域建模

### ISSUE THREAD

**Issue by zhanzy178** [iTraining/documents#10]

**Comment by zhanzongyuan** [comment]
1. Captain是属于Teammates的觉得可以连一个线
2. PlanList建议是和Teammates连线，表示创建关系
3. 中间有个Item是啥，可以解释一下吗

**Comment by Coder-zyq** [comment]
基本和zzy一样，补充说明，item可去掉，其实就是itemDescription,从item到trainingItemList。
可以加一个汇总表，由PlanList和CheckinList,或者加入Community属性中。

**Comment by zhanzongyuan** [comment]
领域建模的图片和说明用一个md文件放到doc下

**Comment by zwk1091** [comment]
感觉captain可以和teammates可以合并，一个用户既可以是一个队伍的队员同时也可以是另一个队伍队长；
TrainingPlan和Check-in感觉也相差不大，是否可以合并...考虑增加一些属性字段来实现合并。。。
