### ISSUE TITLE
UI界面显示及UI交互文档

### ISSUE THREAD

**Issue by zhanzongyuan** [iTraining/documents#9]

**Comment by zwk1091** [comment]
![ui](https://user-images.githubusercontent.com/22057355/39963441-b09e5cee-569d-11e8-8347-d68cadc9fba6.png)

**Comment by Coder-zyq** [comment]
能不能设置一下颜色啊，圆角框啊，整体可以用中大的那个色调，或者淡一点的主色调，中大官网的主色调（0，88，37）#005825.
整体来说，缺少了那个数据分析那一块的UI跳转。

**Comment by zhanzongyuan** [comment]
嗯就是挺丑的。。完工后交给后人继续吧。。

**Comment by zwk1091** [comment]
ojbk
